### ISSUE TITLE
Tests not registering the class as Dogs 

### ISSUE THREAD

**Issue by sheenasany** [learn-co-curriculum/python-p3-orms-putting-it-all-together#4]
### Canvas Link

https://github.com/learn-co-curriculum/python-p3-orms-putting-it-all-together

### Concern

I was running the drop_table() test, using the example from the previous lab, and saw that it gave this error that looked like it was searching for the length of a songs class, but in this case, it supposed to be looking for dogs, and not songs (?). See the errors in red:

![image](https://user-images.githubusercontent.com/105241920/216223015-cd07283a-61a5-4b5a-96ba-424793242272.png)

I tried to look at the tests, and it wasn't showing that it needed songs, but I thought, what the heck, I changed the dropped table to songs, and the errors changed and started looking for the length of the dogs class. See the errors in red:

![image](https://user-images.githubusercontent.com/105241920/216223547-0dc3cdc5-92ba-4a89-a7f5-b973ff4e3706.png)

But then, when I changed it back to drop the table of dogs.... it passed the test. Not sure what kind of glitch this was and why it would cause the table to switch between the two, but thought I'd raise the issue anyway. 

![image](https://user-images.githubusercontent.com/105241920/216223774-02b52979-5ffe-43df-8b14-7705a10b18f4.png)

**Comment by professor-ben** [comment]
We've made some changes in this repo recently to fix a few other minor issues- hopefully that took care of any odd behavior here as well. I'm not seeing a huge problem with the 'songs' trials not passing, but if this persists for the active Dog class, please re-open the issue and we'll take care of it.

Thanks again,
Ben
