### ISSUE TITLE
Changes/updates not implemented to DB

### ISSUE THREAD

**Issue by a-JAVA-chip-frappuccino** [learn-co-curriculum/python-p3-orms-putting-it-all-together#6]
### Canvas Link

https://learning.flatironschool.com/courses/6258/assignments/231388?module_item_id=541565

### Concern

The necessary `CONN.commit()` line is not included in some methods in order to persist updates to the DB.

**Comment by professor-ben** [comment]
Hey Eleanor,

Is this a comment on the solution branch or was this referring to the previous lessons in the module?

Thanks,
Ben

**Comment by a-JAVA-chip-frappuccino** [comment]
It is a comment on the solution branch! Even though the tests pass, there are no updates made to the DB and therefore if students were to look at it, there would be nothing there.

**Comment by professor-ben** [comment]
All set!
